# Generated by Django 4.2.9 on 2024-03-14 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0004_fin_paymentmade_fin_paymentmade_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_paymentmade',
            name='vendor_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fin_paymentmade',
            name='vendor_email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fin_paymentmade',
            name='vendor_gst_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fin_paymentmade',
            name='vendor_gstin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fin_paymentmade',
            name='vendor_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fin_paymentmade',
            name='vendor_source_of_supply',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
