# Generated by Django 4.2.9 on 2024-03-14 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0005_fin_paymentmade_vendor_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fin_paymentmade',
            old_name='reference_number',
            new_name='reference_no',
        ),
    ]
