# Generated by Django 4.2.9 on 2024-03-14 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0006_rename_reference_number_fin_paymentmade_reference_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fin_paymentmade',
            name='bank_account',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
