# Generated by Django 4.2.9 on 2024-03-15 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0008_fin_paymentmade_reference_paymentmade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_paymentmade',
            name='file',
            field=models.FileField(default=None, null=True, upload_to='payment_made'),
        ),
    ]
