# Generated by Django 4.2.9 on 2024-03-16 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0011_fin_paymentmade_balance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_paymentmade',
            name='paymentmade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_payments', to='Finsys_App.fin_paymentmade'),
        ),
    ]
