# Generated by Django 4.2.9 on 2024-03-16 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0012_fin_paymentmade_paymentmade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fin_paymentmade',
            name='vendor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_vendors'),
        ),
    ]
