# Generated by Django 4.2.9 on 2024-03-16 06:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0013_alter_fin_paymentmade_vendor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fin_paymentmade',
            name='balance_amount',
        ),
        migrations.RemoveField(
            model_name='fin_paymentmade',
            name='bill_number',
        ),
        migrations.RemoveField(
            model_name='fin_paymentmade',
            name='date',
        ),
        migrations.RemoveField(
            model_name='fin_paymentmade',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='fin_paymentmade',
            name='paymentmade',
        ),
        migrations.RemoveField(
            model_name='fin_paymentmade',
            name='type',
        ),
        migrations.CreateModel(
            name='Fin_PaymentMadeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Opening Balance', 'Opening Balance'), ('Recurring Bill', 'Recurring Bill'), ('Purchase Bill', 'Purchase Bill'), ('Debit Note', 'Debit Note')], max_length=100)),
                ('date', models.DateField()),
                ('bill_number', models.CharField(max_length=100)),
                ('balance_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_company_details')),
                ('LoginDetails', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_login_details')),
                ('paymentmade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_paymentmade')),
            ],
        ),
    ]
