# Generated by Django 4.2.9 on 2024-03-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0015_fin_paymentmadedetails_vendor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fin_paymentmadedetails',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
