# Generated by Django 4.2.9 on 2024-03-19 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0017_alter_fin_paymentmadedetails_bill_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fin_paymentmadedetails',
            name='balance_amount',
        ),
        migrations.RemoveField(
            model_name='fin_paymentmadedetails',
            name='bill_number',
        ),
        migrations.RemoveField(
            model_name='fin_paymentmadedetails',
            name='date',
        ),
        migrations.RemoveField(
            model_name='fin_paymentmadedetails',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='fin_paymentmadedetails',
            name='type',
        ),
        migrations.AddField(
            model_name='fin_paymentmadedetails',
            name='debit_note_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fin_paymentmadedetails',
            name='debit_note_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fin_paymentmadedetails',
            name='debit_note_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fin_paymentmadedetails',
            name='debit_note_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fin_paymentmadedetails',
            name='opening_balance_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fin_paymentmadedetails',
            name='opening_balance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fin_paymentmadedetails',
            name='opening_balance_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fin_paymentmadedetails',
            name='purchase_bill_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fin_paymentmadedetails',
            name='purchase_bill_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fin_paymentmadedetails',
            name='purchase_bill_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fin_paymentmadedetails',
            name='purchase_bill_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fin_paymentmadedetails',
            name='recurring_bill_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fin_paymentmadedetails',
            name='recurring_bill_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fin_paymentmadedetails',
            name='recurring_bill_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fin_paymentmadedetails',
            name='recurring_bill_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='employee_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 19)),
        ),
        migrations.AlterField(
            model_name='fin_attendance_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 19)),
        ),
        migrations.AlterField(
            model_name='fin_attendance_history',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 19)),
        ),
        migrations.AlterField(
            model_name='holiday_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 19)),
        ),
    ]
