# Generated by Django 4.2.9 on 2024-03-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0018_remove_fin_paymentmadedetails_balance_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_paymentmadedetails',
            name='balance_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fin_paymentmadedetails',
            name='bill_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fin_paymentmadedetails',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fin_paymentmadedetails',
            name='payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fin_paymentmadedetails',
            name='type',
            field=models.CharField(blank=True, choices=[('Opening Balance', 'Opening Balance'), ('Recurring Bill', 'Recurring Bill'), ('Purchase Bill', 'Purchase Bill'), ('Debit Note', 'Debit Note')], max_length=100, null=True),
        ),
    ]
