# Generated by Django 4.2.9 on 2024-03-19 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0019_fin_paymentmadedetails_balance_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fin_paymentmadedetails',
            name='balance_amount',
        ),
        migrations.RemoveField(
            model_name='fin_paymentmadedetails',
            name='bill_number',
        ),
        migrations.RemoveField(
            model_name='fin_paymentmadedetails',
            name='date',
        ),
        migrations.RemoveField(
            model_name='fin_paymentmadedetails',
            name='payment',
        ),
    ]
