# Generated by Django 4.2.9 on 2024-03-21 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0023_fin_debit_note_payment_fin_purchase_bill_payment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fin_debit_note',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='fin_purchase_bill',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='fin_recurring_bills',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='fin_vendors',
            name='opening_balance_payment',
        ),
    ]
