# Generated by Django 4.2.9 on 2024-03-21 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0024_remove_fin_debit_note_payment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_paymentmadedetails',
            name='payment_number',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
