# Generated by Django 4.2.9 on 2024-03-23 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0026_alter_employee_comment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fin_paymentmadedetails',
            name='payment_number',
            field=models.CharField(max_length=50),
        ),
    ]
