# Generated by Django 4.2.9 on 2024-03-23 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0030_alter_fin_paymentmadedetails_payment_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fin_paymentmadedetails',
            name='payment_number',
        ),
        migrations.RemoveField(
            model_name='fin_paymentmadedetails',
            name='paymentmade',
        ),
        migrations.AddField(
            model_name='fin_paymentmade',
            name='payment_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_paymentmadedetails'),
        ),
    ]
