# Generated by Django 4.2.9 on 2024-03-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0031_remove_fin_paymentmadedetails_payment_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fin_paymentmade',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fin_paymentmade',
            name='bill_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fin_paymentmade',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='fin_paymentmade',
            name='payment',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='fin_paymentmade',
            name='type',
            field=models.CharField(choices=[('Opening Balance', 'Opening Balance'), ('Recurring Bill', 'Recurring Bill'), ('Purchase Bill', 'Purchase Bill'), ('Debit Note', 'Debit Note')], max_length=100, null=True),
        ),
    ]
