# Generated by Django 4.2.9 on 2024-03-23 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0032_fin_paymentmade_balance_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fin_paymentmade',
            name='balance_amount',
        ),
        migrations.RemoveField(
            model_name='fin_paymentmade',
            name='bill_number',
        ),
        migrations.RemoveField(
            model_name='fin_paymentmade',
            name='date',
        ),
        migrations.RemoveField(
            model_name='fin_paymentmade',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='fin_paymentmade',
            name='payment_details',
        ),
        migrations.RemoveField(
            model_name='fin_paymentmade',
            name='type',
        ),
        migrations.AddField(
            model_name='fin_paymentmadedetails',
            name='payment_number',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='fin_paymentmadedetails',
            name='paymentmade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Finsys_App.fin_paymentmade'),
        ),
    ]
