# Generated by Django 4.2.9 on 2024-03-25 18:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finsys_App', '0034_fin_debit_note_payment_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fin_debit_note',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='fin_purchase_bill',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='fin_recurring_bills',
            name='payment_amount',
        ),
        migrations.RemoveField(
            model_name='fin_vendors',
            name='payment_amount',
        ),
        migrations.AlterField(
            model_name='employee_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 26)),
        ),
        migrations.AlterField(
            model_name='fin_attendance_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 26)),
        ),
        migrations.AlterField(
            model_name='fin_attendance_history',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 26)),
        ),
        migrations.AlterField(
            model_name='holiday_comment',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 26)),
        ),
    ]
